create table if not exists transport_system_dbloglocktable
(
    id          integer
    primary key,
    locked      boolean not null,
    lockgranted timestamp,
    lockedby    varchar(255)
    );

create table if not exists transport_system_dblogtable
(
    id            varchar(255) not null,
    author        varchar(255) not null,
    filename      varchar(255) not null,
    dateexecuted  timestamp    not null,
    orderexecuted integer      not null,
    exectype      varchar(10)  not null,
    md5sum        varchar(35),
    description   varchar(255),
    comments      varchar(255),
    tag           varchar(255),
    liquibase     varchar(20),
    contexts      varchar(255),
    labels        varchar(255),
    deployment_id varchar(10)
    );

create table if not exists t_passport
(
    id         bigint not null
    constraint pk_passport
    primary key,
    created_at date,
    updated_at date,
    serial     varchar(255),
    number     varchar(255),
    gender     varchar(255)
    );

create table if not exists t_town
(
    town_id    bigint generated always as identity
    constraint pk_town
    primary key,
    created_at date,
    updated_at date,
    name       varchar(255) not null
    );

create table if not exists t_current_location
(
    id           bigint not null
    constraint pk_current_location
    primary key,
    created_at   date,
    updated_at   date,
    town_id BIGINT
    constraint fk_current_location_on_town_id
    references t_town
);

create table if not exists t_destination
(
    id           bigint not null
    constraint pk_destination
    primary key,
    created_at   date,
    updated_at   date,
    town_id BIGINT
    constraint fk_destination_on_town_id
    references t_town
);

create table if not exists t_station
(
    id                   bigint       not null
    constraint pk_stations
    primary key,
    created_at           date,
    updated_at           date,
    station              BIGINT

    );

create table if not exists t_train
(
    id                   BIGINT NOT NULL,
    trainName            VARCHAR(255),
    departureTime        TIMESTAMP WITHOUT TIME ZONE,
    arrival_time         TIMESTAMP WITHOUT TIME ZONE,
    ticket_id            BIGINT,
    seatCount            INTEGER NOT NULL,
    bookedSeatCount      INTEGER NOT NULL,
    currentLocation_id   BIGINT,
    destination_id       BIGINT,
    CONSTRAINT pk_t_train PRIMARY KEY (id)
);


create table if not exists t_ticket
(
    id                      bigint not null
    constraint pk_ticket
    primary key,
    created_at              date,
    updated_at              date,
    user_id                 bigint,
    passport_id             bigint
    constraint fk_ticket_on_passport
    references t_passport,
    booked                  boolean,
    paid                    boolean,
    current_location_id     bigint
    constraint fk_ticket_on_current_location
    references t_current_location,
    destination_location_id bigint
    constraint fk_ticket_on_destination_location
    references t_destination
);

create table if not exists t_user
(
    id          bigint generated always as identity
    constraint pk_users
    primary key,
    created_at  date,
    updated_at  date,
    first_name  varchar(255),
    last_name   varchar(255),
    passport_id bigint
    constraint fk_users_on_passport
    references t_passport,
    ticket_id   bigint
    constraint fk_users_on_ticket
    references t_ticket,
    username    varchar(500),
    password    varchar(500),
    email       varchar(500),
    role        integer
    );

create table if not exists t_role
(
    id   bigint generated by default as identity
    constraint pk_t_role
    primary key,
    name varchar(255)
    );

create table if not exists t_user_role
(
    user_id integer not null
    constraint fk_user_id
    references t_user,
    role_id integer not null
    constraint fk_role_id
    references t_role
);